<?xml version="1.0" encoding="utf-8"?>
<!-- generator="Joomla! 1.5 - Open Source Content Management" -->
<?xml-stylesheet href="/components/com_jcomments/tpl/default/style.css?v=10" type="text/css"?>
<rss version="2.0">
	<channel>
		<title>Jobs</title>
		<description></description>
		<link>http://localhost:8666/index.php?option=com_content&amp;view=category&amp;id=109&amp;layout=blog&amp;Itemid=208</link>
		<lastBuildDate>Thu, 18 Apr 2013 09:33:02 +0000</lastBuildDate>
		<generator>Joomla! 1.5 - Open Source Content Management</generator>
		<language>en-gb</language>
		<item>
			<title>Job offer: Academic Position in Computer Science for Digital Humanities, KU Leuven</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=293:job-offer-academic-position-in-computer-science-for-digital-humanities-ku-leuven&amp;catid=109:jobs&amp;Itemid=208</link>
			<description><![CDATA[<p><img src="http://localhost:8666/images/stories/logo_kuleuven.png" border="0" hspace="10" vspace="10" width="150" align="right" />KU Leuven invites applications for a full-time tenured academic position in Computer Science for Digital Humanities at the Department of Computer Science. <br /><br /><strong>Research</strong>: <br />KU Leuven is looking for a candidate with expertise in applications of computer science in digital humanities. A successful candidate will already have obtained excellent research results in the area of applying computer science techniques in research applications in the digital humanities. For the applied computer science techniques, examples could be data mining, or archiving or disclosure of information from large e-archives, or human-computer interaction, or visualisation techniques, or e-learning.<br />Concerning the applications domains, examples could be the Arts, or the Social or Instructional Sciences. Research experience with the application of multiple techniques from computer Science and/or with multiple application domains in the Humanities or  Behavioral Sciences are considered are a strong added value of the application.<br /><br /><strong>Teaching</strong>:<br />The selected applicant will take on teaching responsibilities in various study programs, in particular for courses on basic computer science techniques for students in the humanities. Apart from this, the applicant will also be asked to teach an advanced course on applications, related to his/her research, in digital humanities. Possibly, the accepted applicant can be asked to teach courses in the Master/Bachelor Computer Science and/or the Master/Bachelor in (Applied) Informatics. Together with an existing team, the successful applicant will further develop courses related to digital humanities. The applicant needs to engage in setting up an interdisciplinary cooperation, both in teaching and in research, on digital humanities.<br /><br /><strong>Offer</strong>:<br />The full-time position can be offered in one of the academic levels (full professor, professor, associate professor, assistant professor), depending on the qualifications of the candidate.</p><p>Please visit the application webpage for further information <a href="http://icts.kuleuven.be/apps/jobsite/vacatures/52409066?lang=en">http://icts.kuleuven.be/apps/jobsite/vacatures/52409066?lang=en </a></p>]]></description>
			<category>Jobs</category>
			<pubDate>Tue, 09 Apr 2013 06:47:05 +0000</pubDate>
		</item>
		<item>
			<title>Job offer: professorship in Digital Humanities, Germany</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=292:job-offer-professorship-in-digital-humanities-germany&amp;catid=109:jobs&amp;Itemid=208</link>
			<description><![CDATA[<p><img src="http://localhost:8666/images/stories/cceh.png" border="0" hspace="10" vspace="10" width="150" align="right" />The Cologne Centre for eHumanities is offering a W1 professorship in Digital Humanities.</p><p>Applicants are expected to have experience in:</p><ul><li><span><span class="hps">Application</span> <span class="hps">of</span> <span class="hps">methods of information technology</span> <span class="hps">in more than</span> <span class="hps">one humanities</span> <span class="hps">subject</span><span>.</span></span></li><li><span><span class="hps">Development and adaptation of</span> <span class="hps">software environments and</span> <span class="hps">software tools.</span></span></li><li><span><span class="hps">Specific</span> <span class="hps">and</span> <span class="hps">interdisciplinary</span> <span class="hps">research methods in</span> <span class="hps">the</span> <span class="hps">humanities.</span></span></li><li><span><span class="hps">Familiarity with</span> <span class="hps">the international research community</span> <span class="hps">of</span> <span class="hps">digital humanities</span><span>.</span></span></li><li><span> <span class="hps">Implementation of research projects</span><span>.</span></span></li><li><span><span class="hps">Teaching</span> <span class="hps">in the</span> <span class="hps">digital humanities</span><span>.</span></span> </li></ul><p>Application deadline: 30 April 2013</p><p>Further information are available under  <a href="http://www.cceh.uni-koeln.de/node/512">http://www.cceh.uni-koeln.de/node/51</a> (in German language) </p>]]></description>
			<category>Jobs</category>
			<pubDate>Tue, 09 Apr 2013 06:08:32 +0000</pubDate>
		</item>
		<item>
			<title>Job offer: Two professorships in Digital Philologies, TU Darmstadt Germany</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=281:job-offer-two-professorships-in-digital-philologies-germany&amp;catid=109:jobs&amp;Itemid=208</link>
			<description><![CDATA[<p><font size="2"><span style="font-size: 10pt">In the past ten years, the Department has established the Digital Humanities with foci in English Corpus and Computational Linguistics as well as German Computer Philology. Throughout this period, the Department has consolidated its position in the digital humanities through internationally networked research activities and the installation of a bilingual Master of Arts program Linguistic and Literary Computing. The specific profile of Digital Humanities as Digital Philologies is going receive further impetus by the installation of a cluster of three professorships representing this discipline. Together with the already existing professorship for German Computational Philology (Andrea Rapp), the two new professorships will form a philology-based cluster of Digital Humanities at TU Darmstadt: <br /></span></font></p><ul><li><font size="2"><span style="font-size: 10pt"> W3 Linguistics with a focus on corpus and computational linguistics, and</span></font></li><li><font size="2"><span style="font-size: 10pt">W2 Literary Studies and Cultural Studies with a focus on Digital Literary Studies / Digital Cultural Studies.</span></font>]]></description>
			<category>Jobs</category>
			<pubDate>Wed, 20 Feb 2013 07:20:01 +0000</pubDate>
		</item>
		<item>
			<title>Job offer: CLARIN ERIC part-time director</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=278:job-offer-clarin-eric-part-time-director&amp;catid=109:jobs&amp;Itemid=208</link>
			<description><![CDATA[<p><img src="http://localhost:8666/images/stories/clarin-eric.jpg" border="0" hspace="10" vspace="10" width="180" height="59" align="right" />The CLARIN European Research Infrastructure Consortium (CLARIN ERIC) has an opening for the part-time position (20% fte) of CLARIN ERIC Director for User Involvement. The chief responsibility of this position is to stimulate, facilitate and coordinate the use of the CLARIN infrastructure, its language resources, and its language services by scholars in the Humanities and Social Sciences on a European scale. For further details please read <a href="http://localhost:8666/images/docs/jobad05feb2013.pdf">this document</a>. The application deadline is 01 March 2013.</p>]]></description>
			<category>Jobs</category>
			<pubDate>Wed, 06 Feb 2013 09:58:39 +0000</pubDate>
		</item>
		<item>
			<title>Job offer: Research Developer at King's College London</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=276:job-offer-research-developer-at-kings-college-london&amp;catid=109:jobs&amp;Itemid=208</link>
			<description><![CDATA[<img src="http://localhost:8666/images/M_images/kings.png" border="0" hspace="10" vspace="10" width="100" height="66" align="right" />The <a href="http://www.kcl.ac.uk/artshums/depts/ddh/index.aspx">Department of Digital Humanities at King's College London</a> is looking for a highly motivated and technically sophisticated individual to join the research and development team. The position will involve data modelling and analysis, plus the design and development of both editorial and administrative tools and public facing web applications, for the second phase of the <a href="http://www.gasconrolls.org/index.html">Gascon Rolls (1317-1468) project</a>, currently being carried out in collaboration with the University of Bordeaux in France. The focus of the work will be on the exploration of historical/technical issues in adapting historical data to wider digital frameworks, the application of geospatial and data mining approaches, new modes of visualisation and multi-device publishing, and the development of a French interface for the project.<br /><br />Closing date for applications is <strong>12 February 2013</strong>.<br /><br />For vacancy details please visit <a href="http://www.kcl.ac.uk/depsta/pertra/vacancy/external/pers_detail.php?jobindex=12763">http://www.kcl.ac.uk/depsta/pertra/vacancy/external/pers_detail.php?jobindex=12763</a>]]></description>
			<category>Jobs</category>
			<pubDate>Sun, 20 Jan 2013 23:00:00 +0000</pubDate>
		</item>
		<item>
			<title>Job offer: Research Developer at King's College London</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=264:job-offer-research-developer-at-kings-college-london&amp;catid=109:jobs&amp;Itemid=208</link>
			<description><![CDATA[<img src="http://localhost:8666/images/M_images/kings.png" border="0" hspace="10" vspace="10" width="100" height="66" align="right" /><font size="2">King´s College London<font size="2">, </font>Department of Digital Humanities, <strong> Centre for e-Research (CeRch) </strong>is seeking a Research Developer in  dynamic web development including implementation of front-end  interfaces. The Researcher will work across two major European  Commission funded research infrastructure projects: the European  Holocaust Research Infrastructure (EHRI) (</font><font size="2"><a href="http://www.ehri-project.eu/">www.ehri-project.eu</a>) and Data Service Infrastructure for  the Social Sciences and the Humanities (Dasish) (<a href="http://dasish.eu/">www.dasish.eu</a>) projects. Her/his role will be to analyse  research practices and translate and implement these in a Virtual Research Environment and research registries.<br /> <br /> The closing date for receipt of applications is <strong>28th December 2012</strong>.<br /> </font><br /> <font size="2"><font size="2">F<font size="2">o</font>r further information please visit the website (<a href="http://www.jobs.ac.uk/job/AFQ273/research-developer">www.jobs.ac.uk/job/AFQ273/research-developer</a>).</font></font>]]></description>
			<category>Jobs</category>
			<pubDate>Thu, 06 Dec 2012 20:54:52 +0000</pubDate>
		</item>
		<item>
			<title>Two postdoc fellowships at the Max Planck Institute for the History of Science, Berlin</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=261:two-postdoc-fellowships-at-the-max-planck-institute-for-the-history-of-science-berlin&amp;catid=109:jobs&amp;Itemid=208</link>
			<description><![CDATA[<font size="2"><span style="font-size: 10pt">The Max Planck Institute  for the History of Science in Berlin, Department II (Lorraine Daston),  announces two postdoctoral fellowships for up to two years, starting  date September 1, 2013. Outstanding junior scholars are invited to  apply.<br /> <br /> The fellowship will be awarded in conjunction with the following two Working Group research projects:<br /> <br /> Historicizing Big Data: <a href="https://email.gwdg.de/owa/redir.aspx?C=kHHHMhZWGUCRehSFaWZ4NnJGq2I8n88I6L_rQwrmtl7Mbnmg5GpjzyCHZbiZak5WkqlyUtyy1nU.&URL=http%3a%2f%2fwww.mpiwg-berlin.mpg.de%2fprojects%2fprojects%2fDeptII_Aronova_Oertzen_Sepkoski_Historicizing" target="_blank">http://www.mpiwg-berlin.mpg.de/projects/projects/DeptII_Aronova_Oertzen_Sepkoski_Historicizing</a> <br /> Science in Circulation<font size="2">: </font><a href="https://email.gwdg.de/owa/redir.aspx?C=kHHHMhZWGUCRehSFaWZ4NnJGq2I8n88I6L_rQwrmtl7Mbnmg5GpjzyCHZbiZak5WkqlyUtyy1nU.&URL=http%3a%2f%2fwww.mpiwg-berlin.mpg.de%2fen%2fresearch%2fprojects%2fDeptII_Science_in_Circulation%2findex_html" target="_blank">http://www.mpiwg-berlin.mpg.de/en/research/projects/DeptII_Science_in_Circulation/index_html</a> <br /> Candidates should hold a doctorate in the history of science or a  related field at the time the fellowship begins; the Ph.D. degree should  have been awarded in 2010 or later.<br /> <br /> The Max Planck Institute for the History of Science is an international  and interdisciplinary research institute (website). It is expected that  candidates will be able to present their own work and discuss that of  others fluently in English. Applications may however be submitted in  German, English, or French.<br /> </span></font>]]></description>
			<category>Jobs</category>
			<pubDate>Mon, 26 Nov 2012 07:12:18 +0000</pubDate>
		</item>
		<item>
			<title>TCD: Software Engineer for DERI</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=252:tcd-software-engineer-for-deri&amp;catid=109:jobs&amp;Itemid=208</link>
			<description><![CDATA[<img src="http://localhost:8666/images/stories/deri_ie_head.gif" border="0" title="Logo DERI" hspace="10" vspace="10" width="180" height="58" align="right" />Trinity College Dublin is recruiting for a Software Engineer for the <a href="http://www.deri.org/" title="Link to DERI website">Digital Repository of Ireland</a>.<br /><br />• Post Status: Contract up to up to 31st August, 2015<br />• Post Summary: Developing and deploying advanced IT systems as part of the Digital Repository Ireland (DRI)<br />• Department/Faculty: High Performance & Research Computing, ISS<br />• Location: Lloyd Building, Main Campus, Trinity College Dublin<br />• Salary: This post will be made on the Administrative Officer 3/2 in line with current Government Pay Policy<br />• Closing Date: 12 Noon on Friday 5th October, 2012<br /><br />Application details are available at the link below.<br />More details are available at <a href="http://www.tchpc.tcd.ie/node/1077">http://www.tchpc.tcd.ie/node/1077</a> .]]></description>
			<category>Jobs</category>
			<pubDate>Mon, 01 Oct 2012 13:27:36 +0000</pubDate>
		</item>
		<item>
			<title>PhD scholarships, Aarhus University</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=244:phd-scholarships-aarhus-university&amp;catid=109:jobs&amp;Itemid=208</link>
			<description><![CDATA[<p><img src="http://localhost:8666/images/stories/aarhus_university.jpg" border="0" alt="Logo Aarhus University" hspace="10" vspace="10" width="180" height="81" align="right" />PhD scholarships for the PhD programme – open notice (4+4 and 5+3 scheme)<br /><br />A number of SU PhD scholarships SU (4+4) and PhD scholarships (5+3) are announced at the<strong> Graduate School, Arts, Faculty of Arts at Aarhus University</strong> provided the necessary funding is available. These scholarships are available as of <strong>1 February 2013 for a period of up to three years (5+3) and of up to four years (4+4)</strong>. Candidates who are awarded the scholarship must commence their PhD programme on1 February 2013.<br />Scholarships are available in all fields and areas of research at the Faculty of Arts.<br />A prerequisite for allocation of a PhD scholarship/SU PhD scholarship is that you are enrolled as a PhD student at the Graduate School of Arts.<br /><br />The PhD student must complete the studies in accordance with the current regulations for the PhD degree programme, currently the Ministerial Order of 14 January 2008 on the PhD Programme at the Universities: <a href="http://talent.au.dk/phd/arts/rulesandforms/thephddegreeprogramme/">http://talent.au.dk/phd/arts/rulesandforms/thephddegreeprogramme/</a><br />Description of the Graduate School’s PhD programme (4+4 and 5+3): <a href="http://talent.au.dk/phd/arts/phdstudystructure/" target="_self">http://talent.au.dk/phd/arts/phdstudystructure/</a></p>]]></description>
			<category>Jobs</category>
			<pubDate>Fri, 14 Sep 2012 09:56:55 +0000</pubDate>
		</item>
		<item>
			<title>KCL DDH: 3 research developers</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=241:kcl-ddh-3-research-developers&amp;catid=109:jobs&amp;Itemid=208</link>
			<description><![CDATA[<p><img src="http://localhost:8666/images/M_images/kings.png" border="0" alt="Logo KCL" hspace="10" vspace="10" width="120" align="right" />The Department of Digital Humanities (DDH) is looking for a number of skilled developers to join its  Research and Development team.  These posts all involve implementation  and functional design work (in collaboration with other members of the  R&D team and external partners) across two - three varied and  challenging research projects.</p><p><font size="2"><span style="font-size: 10pt">The closing date is <strong>13th September 2012</strong> with interviews to be held during the week beginning 17th September 2012.</span></font> </p><p>Please follow this link to find out details: <a href="http://www.jobs.ac.uk/enhanced/linking/kings/aug2012/linkingpage.html" title="Link to the DDH webpage">http://www.jobs.ac.uk/enhanced/linking/kings/aug2012/linkingpage.html</a></p>]]></description>
			<category>Jobs</category>
			<pubDate>Wed, 05 Sep 2012 07:23:20 +0000</pubDate>
		</item>
	</channel>
</rss>
