<?xml version="1.0" encoding="utf-8"?>
<!-- generator="Joomla! 1.5 - Open Source Content Management" -->
<?xml-stylesheet href="/components/com_jcomments/tpl/default/style.css?v=10" type="text/css"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:base="http://localhost:8666/index.php" xml:lang="en-gb">
	<title type="text">Home</title>
	<subtitle type="text"></subtitle>
	<link rel="alternate" type="text/html" href="/index.php?option=com_content&amp;view=frontpage&amp;Itemid=113"/>
	<id>/index.php?option=com_content&amp;view=frontpage&amp;Itemid=113</id>
	<updated>2013-04-18T09:30:41Z</updated>
	<generator uri="http://joomla.org" version="1.5">Joomla! 1.5 - Open Source Content Management</generator>
<link rel="self" type="application/atom+xml" href="/" />
	<entry>
		<title>CFP: Cultural Heritage, Creative Tools and Archives Workshop</title>
		<link rel="alternate" type="text/html" href="/index.php?option=com_content&amp;view=article&amp;id=291:cfp-cultural-heritage-creative-tools-and-archives-workshop&amp;catid=3:dariah&amp;Itemid=197"/>
		<published>2013-04-03T10:07:27Z</published>
		<updated>2013-04-03T10:07:27Z</updated>
		<id>/index.php?option=com_content&amp;amp;view=article&amp;amp;id=291:cfp-cultural-heritage-creative-tools-and-archives-workshop&amp;amp;catid=3:dariah&amp;amp;Itemid=197</id>
		<summary type="html">&lt;p&gt;&lt;a href=&quot;http://dighumlab.dk/&quot;&gt;&lt;img src=&quot;images/M_images/dighumlab.jpg&quot; border=&quot;0&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; width=&quot;200&quot; height=&quot;56&quot; align=&quot;right&quot; /&gt;&lt;img src=&quot;images/stories/dcu_logo_en.png&quot; border=&quot;0&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; width=&quot;200&quot; align=&quot;right&quot; /&gt;DIGHUMLAB DK&lt;/a&gt; and the &lt;a href=&quot;http://www.dcu.gr/&quot;&gt;DIGITAL CURATION UNIT&lt;/a&gt; Athens are pleased to invite you to submit to a DARIAH associated 2 day workshop on CULTURAL HERITAGE, CREATIVE TOOLS AND ARCHIVES.&lt;br /&gt;The workshop is open to all but we in particular invite participants drawn in the first instance from the DARIAH, ARIADNE, CENDARI and NeDiMAH and other EU cultural heritage networks. We envisage it will foster the growth of a community of practice in the field of digital heritage and digital humanities, leading to closer cooperation between participants and helping attendees develop tools and methods that can be used by the wider community.&lt;/p&gt;&lt;p&gt;&lt;strong&gt;Central topics:&lt;/strong&gt;&lt;/p&gt;&lt;ul&gt;&lt;li&gt;    Presentation of digital heritage tools and infrastructures (database, knowledge representation, analysis).&lt;/li&gt;&lt;li&gt;    GIS, 3D graphic reconstruction, high end imaging.&lt;/li&gt;&lt;li&gt;    Ontology related to archives and database storage for material and visual culture, etc. and how best to share data and tools across European countries and partners.&lt;/li&gt;&lt;li&gt;    Database and infrastructure support for fieldwork (cf. issues of data collecting and representation, excavation and survey data management, recording &quot;information at the trowel's edge&quot; to coin Ian Hodder, how to best process survey and long series datasets etc.).&lt;/li&gt;&lt;li&gt;    Discussion on further collaboration and how to influence EU policy in digital heritage-cultural heritage matters.&lt;/li&gt;&lt;/ul&gt;&lt;strong&gt;Presentation formats:&lt;/strong&gt;&lt;br /&gt;&lt;ul&gt;&lt;li&gt;    Project presentation 20 minutes.&lt;/li&gt;&lt;li&gt;    Demonstration 20 minutes of tool or method or project.&lt;/li&gt;&lt;li&gt;    Paper presentation 20 minutes presentation. Final papers may be published in a journal (to be advised).&lt;/li&gt;&lt;li&gt;    Panel 40-60 minutes involving 3-5 speakers.</summary>
		<content type="html">&lt;p&gt;&lt;a href=&quot;http://dighumlab.dk/&quot;&gt;&lt;img src=&quot;images/M_images/dighumlab.jpg&quot; border=&quot;0&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; width=&quot;200&quot; height=&quot;56&quot; align=&quot;right&quot; /&gt;&lt;img src=&quot;images/stories/dcu_logo_en.png&quot; border=&quot;0&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; width=&quot;200&quot; align=&quot;right&quot; /&gt;DIGHUMLAB DK&lt;/a&gt; and the &lt;a href=&quot;http://www.dcu.gr/&quot;&gt;DIGITAL CURATION UNIT&lt;/a&gt; Athens are pleased to invite you to submit to a DARIAH associated 2 day workshop on CULTURAL HERITAGE, CREATIVE TOOLS AND ARCHIVES.&lt;br /&gt;The workshop is open to all but we in particular invite participants drawn in the first instance from the DARIAH, ARIADNE, CENDARI and NeDiMAH and other EU cultural heritage networks. We envisage it will foster the growth of a community of practice in the field of digital heritage and digital humanities, leading to closer cooperation between participants and helping attendees develop tools and methods that can be used by the wider community.&lt;/p&gt;&lt;p&gt;&lt;strong&gt;Central topics:&lt;/strong&gt;&lt;/p&gt;&lt;ul&gt;&lt;li&gt;    Presentation of digital heritage tools and infrastructures (database, knowledge representation, analysis).&lt;/li&gt;&lt;li&gt;    GIS, 3D graphic reconstruction, high end imaging.&lt;/li&gt;&lt;li&gt;    Ontology related to archives and database storage for material and visual culture, etc. and how best to share data and tools across European countries and partners.&lt;/li&gt;&lt;li&gt;    Database and infrastructure support for fieldwork (cf. issues of data collecting and representation, excavation and survey data management, recording &quot;information at the trowel's edge&quot; to coin Ian Hodder, how to best process survey and long series datasets etc.).&lt;/li&gt;&lt;li&gt;    Discussion on further collaboration and how to influence EU policy in digital heritage-cultural heritage matters.&lt;/li&gt;&lt;/ul&gt;&lt;strong&gt;Presentation formats:&lt;/strong&gt;&lt;br /&gt;&lt;ul&gt;&lt;li&gt;    Project presentation 20 minutes.&lt;/li&gt;&lt;li&gt;    Demonstration 20 minutes of tool or method or project.&lt;/li&gt;&lt;li&gt;    Paper presentation 20 minutes presentation. Final papers may be published in a journal (to be advised).&lt;/li&gt;&lt;li&gt;    Panel 40-60 minutes involving 3-5 speakers.</content>
	</entry>
	<entry>
		<title>Hack4LT, 4 - 5 April 2013, Vilnius, Lithuania</title>
		<link rel="alternate" type="text/html" href="/index.php?option=com_content&amp;view=article&amp;id=290:hack4lt-4-5-april-2013-vilnius-lithiania&amp;catid=3:dariah&amp;Itemid=197"/>
		<published>2013-03-11T09:12:35Z</published>
		<updated>2013-03-11T09:12:35Z</updated>
		<id>/index.php?option=com_content&amp;amp;view=article&amp;amp;id=290:hack4lt-4-5-april-2013-vilnius-lithiania&amp;amp;catid=3:dariah&amp;amp;Itemid=197</id>
		<summary type="html">&lt;p&gt;&lt;img src=&quot;images/stories/hack4lt_agenda_seite_1.jpg&quot; border=&quot;0&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; height=&quot;200&quot; align=&quot;right&quot; /&gt;&lt;strong&gt;Hack4LT&lt;/strong&gt;: The first cultural heritage and digital humanities orientated hackathon in Lithuania will take place on 04 - 05 April 2013 in Vilnius, Lithuania&lt;br /&gt; &lt;strong&gt;Inspired by:&lt;/strong&gt; EUROPEANA and DARIAH&lt;br /&gt; &lt;strong&gt;Organisators:&lt;/strong&gt; Vilnius University Faculty of Communication (VUFC) (&lt;a href=&quot;http://www.kf.vu.lt/en&quot;&gt;http://www.kf.vu.lt/en&lt;/a&gt;) and Vilnius University Library (VUL) &lt;a href=&quot;(http://www.mb.vu.lt/en/titulinis&quot;&gt;(http://www.mb.vu.lt/en/titulinis&lt;/a&gt;)&lt;br /&gt;Partners: M. Mažvydas National Library of Lithuania (NLL) (&lt;a href=&quot;http://www.lnb.lt/en/&quot;&gt;http://www.lnb.lt/en/&lt;/a&gt;) and „Dizi“ (&lt;a href=&quot;http://www.dizi.lt/heritage/index_en.php&quot;&gt;http://www.dizi.lt/heritage/index_en.php&lt;/a&gt;)&lt;br /&gt;Sponsors: Vilnius University (VU) (&lt;a href=&quot;http://www.vu.lt/en&quot;&gt;http://www.vu.lt/en&lt;/a&gt;) and &quot;Asseco Lietuva&quot; (&lt;a href=&quot;http://www.sintagma.lt/sintagma/selectLanguage.do?language=en&quot;&gt;http://www.sintagma.lt/sintagma/selectLanguage.do?language=en&lt;/a&gt;).&lt;br /&gt;&lt;strong&gt;Venue:&lt;/strong&gt; National Open Access Scholarly Communication and Information Center (http://www.mkic.mb.vu.lt/en/), Address: Saulėtekio av. 5, Vilnius, Lithuania (https://foursquare.com/v/mkic--vilniaus-universiteto-biblioteka/5110af35e4b00d9b65a437c1&lt;br /&gt;&lt;a href=&quot;https://email.gwdg.de/owa/redir.aspx?C=l4lMj_G9RUWmr68PN0XBso9uktTD8c8I1I_q3wjVcFdN0szArdK23ElhtjUJx9pn9VrTPajroQo.&amp;URL=https%3a%2f%2ffoursquare.com%2fv%2fmkic--vilniaus-universiteto-biblioteka%2f5110af35e4b00d9b65a437c1&quot; target=&quot;_blank&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;strong&gt;Description:&lt;/strong&gt;&lt;br /&gt; Hack4LT is a two-day event intended to stimulate the collaboration  between Humanities' scholars and software developers. Its aim is  targeted towards the technology driven experimentation with an existing  EUROPEANA data sets connecting various kinds of digitized  cultural heritage resources from the European museums, libraries,  archives, etc. Free access to these resources stimulates a broad public  interest in the European culture and challenges cultural institutions to  seek new ways of engaging people, as well as  to develops tools in this space. Furthermore, because of the richness  of EUROPEANA collection and the nature of a preserved digital content it  is considered to be a valuable data source for the researchers of the  Digital Humanities and enhances digitally-enabled  research in this area.&lt;/p&gt;</summary>
		<content type="html">&lt;p&gt;&lt;img src=&quot;images/stories/hack4lt_agenda_seite_1.jpg&quot; border=&quot;0&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; height=&quot;200&quot; align=&quot;right&quot; /&gt;&lt;strong&gt;Hack4LT&lt;/strong&gt;: The first cultural heritage and digital humanities orientated hackathon in Lithuania will take place on 04 - 05 April 2013 in Vilnius, Lithuania&lt;br /&gt; &lt;strong&gt;Inspired by:&lt;/strong&gt; EUROPEANA and DARIAH&lt;br /&gt; &lt;strong&gt;Organisators:&lt;/strong&gt; Vilnius University Faculty of Communication (VUFC) (&lt;a href=&quot;http://www.kf.vu.lt/en&quot;&gt;http://www.kf.vu.lt/en&lt;/a&gt;) and Vilnius University Library (VUL) &lt;a href=&quot;(http://www.mb.vu.lt/en/titulinis&quot;&gt;(http://www.mb.vu.lt/en/titulinis&lt;/a&gt;)&lt;br /&gt;Partners: M. Mažvydas National Library of Lithuania (NLL) (&lt;a href=&quot;http://www.lnb.lt/en/&quot;&gt;http://www.lnb.lt/en/&lt;/a&gt;) and „Dizi“ (&lt;a href=&quot;http://www.dizi.lt/heritage/index_en.php&quot;&gt;http://www.dizi.lt/heritage/index_en.php&lt;/a&gt;)&lt;br /&gt;Sponsors: Vilnius University (VU) (&lt;a href=&quot;http://www.vu.lt/en&quot;&gt;http://www.vu.lt/en&lt;/a&gt;) and &quot;Asseco Lietuva&quot; (&lt;a href=&quot;http://www.sintagma.lt/sintagma/selectLanguage.do?language=en&quot;&gt;http://www.sintagma.lt/sintagma/selectLanguage.do?language=en&lt;/a&gt;).&lt;br /&gt;&lt;strong&gt;Venue:&lt;/strong&gt; National Open Access Scholarly Communication and Information Center (http://www.mkic.mb.vu.lt/en/), Address: Saulėtekio av. 5, Vilnius, Lithuania (https://foursquare.com/v/mkic--vilniaus-universiteto-biblioteka/5110af35e4b00d9b65a437c1&lt;br /&gt;&lt;a href=&quot;https://email.gwdg.de/owa/redir.aspx?C=l4lMj_G9RUWmr68PN0XBso9uktTD8c8I1I_q3wjVcFdN0szArdK23ElhtjUJx9pn9VrTPajroQo.&amp;URL=https%3a%2f%2ffoursquare.com%2fv%2fmkic--vilniaus-universiteto-biblioteka%2f5110af35e4b00d9b65a437c1&quot; target=&quot;_blank&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;strong&gt;Description:&lt;/strong&gt;&lt;br /&gt; Hack4LT is a two-day event intended to stimulate the collaboration  between Humanities' scholars and software developers. Its aim is  targeted towards the technology driven experimentation with an existing  EUROPEANA data sets connecting various kinds of digitized  cultural heritage resources from the European museums, libraries,  archives, etc. Free access to these resources stimulates a broad public  interest in the European culture and challenges cultural institutions to  seek new ways of engaging people, as well as  to develops tools in this space. Furthermore, because of the richness  of EUROPEANA collection and the nature of a preserved digital content it  is considered to be a valuable data source for the researchers of the  Digital Humanities and enhances digitally-enabled  research in this area.&lt;/p&gt;</content>
	</entry>
	<entry>
		<title>Italy signed Memorandum of Understanding</title>
		<link rel="alternate" type="text/html" href="/index.php?option=com_content&amp;view=article&amp;id=289:italy-signed-memorandum-of-understanding&amp;catid=3:dariah&amp;Itemid=197"/>
		<published>2013-03-08T13:01:47Z</published>
		<updated>2013-03-08T13:01:47Z</updated>
		<id>/index.php?option=com_content&amp;amp;view=article&amp;amp;id=289:italy-signed-memorandum-of-understanding&amp;amp;catid=3:dariah&amp;amp;Itemid=197</id>
		<summary type="html">&lt;p&gt;&lt;a href=&quot;http://www.cnr.it/sitocnr/Englishversion/Englishversion.html&quot;&gt;&lt;img src=&quot;images/stories/dariah-it-logo-no-tagline-rgb.png&quot; border=&quot;0&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; width=&quot;180&quot; align=&quot;right&quot; /&gt;&lt;/a&gt;We are delighted to announce that Italy has signed the Memorandum of Understanding (MoU) formally expressing their interest in participating in DARIAH.&lt;/p&gt;&lt;p&gt;DARIAH-IT activities will be coordinated by the the &lt;a href=&quot;http://www.cnr.it/sitocnr/Englishversion/Englishversion.html&quot;&gt;National Research Council&lt;/a&gt;.&lt;/p&gt;</summary>
		<content type="html">&lt;p&gt;&lt;a href=&quot;http://www.cnr.it/sitocnr/Englishversion/Englishversion.html&quot;&gt;&lt;img src=&quot;images/stories/dariah-it-logo-no-tagline-rgb.png&quot; border=&quot;0&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; width=&quot;180&quot; align=&quot;right&quot; /&gt;&lt;/a&gt;We are delighted to announce that Italy has signed the Memorandum of Understanding (MoU) formally expressing their interest in participating in DARIAH.&lt;/p&gt;&lt;p&gt;DARIAH-IT activities will be coordinated by the the &lt;a href=&quot;http://www.cnr.it/sitocnr/Englishversion/Englishversion.html&quot;&gt;National Research Council&lt;/a&gt;.&lt;/p&gt;</content>
	</entry>
	<entry>
		<title> Bamboo DiRT and DH Commons looking for DARIAH representatives</title>
		<link rel="alternate" type="text/html" href="/index.php?option=com_content&amp;view=article&amp;id=288:-bamboo-dirt-and-dh-commons-looking-for-dariah-representatives&amp;catid=3:dariah&amp;Itemid=197"/>
		<published>2013-03-08T07:31:04Z</published>
		<updated>2013-03-08T07:31:04Z</updated>
		<id>/index.php?option=com_content&amp;amp;view=article&amp;amp;id=288:-bamboo-dirt-and-dh-commons-looking-for-dariah-representatives&amp;amp;catid=3:dariah&amp;amp;Itemid=197</id>
		<summary type="html">&lt;p&gt;&lt;img src=&quot;images/stories/dhcommons_logo.jpg&quot; border=&quot;0&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; width=&quot;200&quot; align=&quot;right&quot; /&gt; &lt;img src=&quot;images/stories/bamboo_dirt.jpg&quot; border=&quot;0&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; width=&quot;200&quot; height=&quot;42&quot; align=&quot;right&quot; /&gt;Bamboo DiRT and DH Commons are looking for DARIAH representatives. &lt;/p&gt;&lt;p&gt;1. A DARIAH representative on the board of &lt;a href=&quot;http://dirt.projectbamboo.org/&quot;&gt;Bamboo DiRT&lt;/a&gt;&lt;/p&gt;&lt;p&gt;Quinn Dombroski from Bamboo DiRT would be happy to add contents from DARIAH directory of tools (including DARIAH seal), and to welcome a DARIAH member in her editorial board.&lt;/p&gt;&lt;p&gt;2. A DARIAH representative as co-editor for&lt;a href=&quot;http://dhcommons.org/&quot;&gt; DHCommons&lt;/a&gt;&lt;/p&gt;&lt;p&gt;The role of the co-editor coming from a non US and preferably non English speaking country would be to work on a weekly basis on collecting reviews and suggesting new projects in the database. DHCommons is seeking a co-editor with a different speciality than co-editor Ryan Cordell who is active in the literature, geolocalisation in texts, social networks areas.&lt;/p&gt;&lt;p&gt;If you are interested, please contact  Marin Dacos (&lt;a href=&quot;mailto:marin.dacos@openedition.org&quot;&gt;marin.dacos at openedition.org&lt;/a&gt;) or Erik Champion (&lt;a href=&quot;mailto:echa@adm.au.dk&quot;&gt;echa at adm.au.dk&lt;/a&gt;)&lt;/p&gt;</summary>
		<content type="html">&lt;p&gt;&lt;img src=&quot;images/stories/dhcommons_logo.jpg&quot; border=&quot;0&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; width=&quot;200&quot; align=&quot;right&quot; /&gt; &lt;img src=&quot;images/stories/bamboo_dirt.jpg&quot; border=&quot;0&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; width=&quot;200&quot; height=&quot;42&quot; align=&quot;right&quot; /&gt;Bamboo DiRT and DH Commons are looking for DARIAH representatives. &lt;/p&gt;&lt;p&gt;1. A DARIAH representative on the board of &lt;a href=&quot;http://dirt.projectbamboo.org/&quot;&gt;Bamboo DiRT&lt;/a&gt;&lt;/p&gt;&lt;p&gt;Quinn Dombroski from Bamboo DiRT would be happy to add contents from DARIAH directory of tools (including DARIAH seal), and to welcome a DARIAH member in her editorial board.&lt;/p&gt;&lt;p&gt;2. A DARIAH representative as co-editor for&lt;a href=&quot;http://dhcommons.org/&quot;&gt; DHCommons&lt;/a&gt;&lt;/p&gt;&lt;p&gt;The role of the co-editor coming from a non US and preferably non English speaking country would be to work on a weekly basis on collecting reviews and suggesting new projects in the database. DHCommons is seeking a co-editor with a different speciality than co-editor Ryan Cordell who is active in the literature, geolocalisation in texts, social networks areas.&lt;/p&gt;&lt;p&gt;If you are interested, please contact  Marin Dacos (&lt;a href=&quot;mailto:marin.dacos@openedition.org&quot;&gt;marin.dacos at openedition.org&lt;/a&gt;) or Erik Champion (&lt;a href=&quot;mailto:echa@adm.au.dk&quot;&gt;echa at adm.au.dk&lt;/a&gt;)&lt;/p&gt;</content>
	</entry>
	<entry>
		<title>THATCamp London, registration now open</title>
		<link rel="alternate" type="text/html" href="/index.php?option=com_content&amp;view=article&amp;id=287:thatcamp-london-registration-now-open&amp;catid=3:dariah&amp;Itemid=197"/>
		<published>2013-02-28T07:20:01Z</published>
		<updated>2013-02-28T07:20:01Z</updated>
		<id>/index.php?option=com_content&amp;amp;view=article&amp;amp;id=287:thatcamp-london-registration-now-open&amp;amp;catid=3:dariah&amp;amp;Itemid=197</id>
		<summary type="html">&lt;p&gt;THAT Camp London is now open for registration. This one-day unconference will take place on 14 April 2013 at the British Library. This event coincides with the &lt;a href=&quot;https://uk.wikimedia.org/wiki/GLAM-WIKI_2013&quot;&gt;GLAM-WIKI conference&lt;/a&gt;, which runs on Friday 12 and Saturday 13 April 2013.&lt;/p&gt;&lt;p&gt;For further information please visit this page: &lt;a href=&quot;http://london2013.thatcamp.org/&quot;&gt;http://london2013.thatcamp.org/ &lt;/a&gt;&lt;/p&gt;&lt;p&gt;Further upcoming THATCamps can be found here: &lt;a href=&quot;http://thatcamp.org/en/&quot;&gt;http://thatcamp.org/en/ &lt;/a&gt;&lt;/p&gt;</summary>
		<content type="html">&lt;p&gt;THAT Camp London is now open for registration. This one-day unconference will take place on 14 April 2013 at the British Library. This event coincides with the &lt;a href=&quot;https://uk.wikimedia.org/wiki/GLAM-WIKI_2013&quot;&gt;GLAM-WIKI conference&lt;/a&gt;, which runs on Friday 12 and Saturday 13 April 2013.&lt;/p&gt;&lt;p&gt;For further information please visit this page: &lt;a href=&quot;http://london2013.thatcamp.org/&quot;&gt;http://london2013.thatcamp.org/ &lt;/a&gt;&lt;/p&gt;&lt;p&gt;Further upcoming THATCamps can be found here: &lt;a href=&quot;http://thatcamp.org/en/&quot;&gt;http://thatcamp.org/en/ &lt;/a&gt;&lt;/p&gt;</content>
	</entry>
	<entry>
		<title>First CENDARI Summer School, 22 - 26 July 2013</title>
		<link rel="alternate" type="text/html" href="/index.php?option=com_content&amp;view=article&amp;id=285:first-cendari-summer-school-22-26-july-2013&amp;catid=3:dariah&amp;Itemid=197"/>
		<published>2013-02-22T09:12:52Z</published>
		<updated>2013-02-22T09:12:52Z</updated>
		<id>/index.php?option=com_content&amp;amp;view=article&amp;amp;id=285:first-cendari-summer-school-22-26-july-2013&amp;amp;catid=3:dariah&amp;amp;Itemid=197</id>
		<summary type="html">&lt;img src=&quot;images/stories/cendari.jpg&quot; border=&quot;0&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; width=&quot;180&quot; height=&quot;62&quot; align=&quot;right&quot; /&gt;The &lt;a href=&quot;http://www.cendari.eu/&quot;&gt;CENDARI&lt;/a&gt; (Collaborative European Digital Archive Infrastructure) project, in collaboration with the COST Action: IS 1005, 'Medioevo Europeo: Medieval Studies and Technological Resources', will host the first of three annual CENDARI Summer Schools, 22 - 26 July 2013 in Florence, Italy. The Summer School, entitled &lt;strong&gt;Historical Sources &amp; Transnational Approaches to European History&lt;/strong&gt;, will invite participants to address specifically how CENDARI aims to resolve the difficulties of historical research through the application of digital technologies and methods. For more information and to &lt;strong&gt;apply before the 15th April 2013&lt;/strong&gt;, please visit &lt;a href=&quot;http://www.cendari.eu/news-events/summer-school-2013/&quot;&gt;http://www.cendari.eu/news-events/summer-school-2013/&lt;/a&gt;.&lt;br /&gt;&lt;br /&gt;Sessions will apply the concept of 'transnational moments' to examine ways in which historical research is complicated by the nature of material records of the past. The Summer School will provide a context for the various collections-level challenges to transnational history, such as how to identify sources that have become 'hidden' or lost through accidents of history. Researchers will examine the linguistic, quantitative and methodological challenges facing them today.&lt;br /&gt;</summary>
		<content type="html">&lt;img src=&quot;images/stories/cendari.jpg&quot; border=&quot;0&quot; hspace=&quot;10&quot; vspace=&quot;10&quot; width=&quot;180&quot; height=&quot;62&quot; align=&quot;right&quot; /&gt;The &lt;a href=&quot;http://www.cendari.eu/&quot;&gt;CENDARI&lt;/a&gt; (Collaborative European Digital Archive Infrastructure) project, in collaboration with the COST Action: IS 1005, 'Medioevo Europeo: Medieval Studies and Technological Resources', will host the first of three annual CENDARI Summer Schools, 22 - 26 July 2013 in Florence, Italy. The Summer School, entitled &lt;strong&gt;Historical Sources &amp; Transnational Approaches to European History&lt;/strong&gt;, will invite participants to address specifically how CENDARI aims to resolve the difficulties of historical research through the application of digital technologies and methods. For more information and to &lt;strong&gt;apply before the 15th April 2013&lt;/strong&gt;, please visit &lt;a href=&quot;http://www.cendari.eu/news-events/summer-school-2013/&quot;&gt;http://www.cendari.eu/news-events/summer-school-2013/&lt;/a&gt;.&lt;br /&gt;&lt;br /&gt;Sessions will apply the concept of 'transnational moments' to examine ways in which historical research is complicated by the nature of material records of the past. The Summer School will provide a context for the various collections-level challenges to transnational history, such as how to identify sources that have become 'hidden' or lost through accidents of history. Researchers will examine the linguistic, quantitative and methodological challenges facing them today.&lt;br /&gt;</content>
	</entry>
	<entry>
		<title>OpenEdition Books! Now open</title>
		<link rel="alternate" type="text/html" href="/index.php?option=com_content&amp;view=article&amp;id=283:openedition-books-now-open&amp;catid=3:dariah&amp;Itemid=197"/>
		<published>2013-02-22T08:16:27Z</published>
		<updated>2013-02-22T08:16:27Z</updated>
		<id>/index.php?option=com_content&amp;amp;view=article&amp;amp;id=283:openedition-books-now-open&amp;amp;catid=3:dariah&amp;amp;Itemid=197</id>
		<summary type="html">After &lt;a href=&quot;http://www.openedition.org/&quot;&gt;Revues.org &lt;/a&gt;(1999), &lt;a href=&quot;http://calenda.org/&quot;&gt;Calenda&lt;/a&gt; (2000) and &lt;a href=&quot;http://hypotheses.org/&quot;&gt;Hypothèses&lt;/a&gt; (2008), OpenEdition’s fourth platform appeared Wednesday 20th February 2013. &lt;a href=&quot;http://books.openedition.org/&quot;&gt;OpenEdition Books&lt;/a&gt; is the final addition to our comprehensive series of publishing platforms for the humanities and social sciences. The new service is the book distribution platform on the OpenEdition portal, a non-profit-making initiative whose aim is to develop Open Access to research results in the humanities, social sciences and beyond. The service is not an ideological gesture. It is a genuine academic program, in which ideas are seen as seeds that require constant cross-fertilisation to attain their full potential. OpenEdition is run by the Centre for Open Electronic Publishing, the Université d’Aix-Marseille, the EHESS and the Université d’Avignon, and financed by the French national research agency within the framework of their Facilities of Excellence program.&lt;br /&gt;</summary>
		<content type="html">After &lt;a href=&quot;http://www.openedition.org/&quot;&gt;Revues.org &lt;/a&gt;(1999), &lt;a href=&quot;http://calenda.org/&quot;&gt;Calenda&lt;/a&gt; (2000) and &lt;a href=&quot;http://hypotheses.org/&quot;&gt;Hypothèses&lt;/a&gt; (2008), OpenEdition’s fourth platform appeared Wednesday 20th February 2013. &lt;a href=&quot;http://books.openedition.org/&quot;&gt;OpenEdition Books&lt;/a&gt; is the final addition to our comprehensive series of publishing platforms for the humanities and social sciences. The new service is the book distribution platform on the OpenEdition portal, a non-profit-making initiative whose aim is to develop Open Access to research results in the humanities, social sciences and beyond. The service is not an ideological gesture. It is a genuine academic program, in which ideas are seen as seeds that require constant cross-fertilisation to attain their full potential. OpenEdition is run by the Centre for Open Electronic Publishing, the Université d’Aix-Marseille, the EHESS and the Université d’Avignon, and financed by the French national research agency within the framework of their Facilities of Excellence program.&lt;br /&gt;</content>
	</entry>
	<entry>
		<title>PhD scholarship  in Digital Heritage and Virtual Culture by DIGHUMLAB and Aarhus University</title>
		<link rel="alternate" type="text/html" href="/index.php?option=com_content&amp;view=article&amp;id=284:phd-scholarship-in-digital-heritage-and-virtual-culture-by-dighumlab-and-aarhus-university&amp;catid=3:dariah&amp;Itemid=197"/>
		<published>2013-02-22T07:29:29Z</published>
		<updated>2013-02-22T07:29:29Z</updated>
		<id>/index.php?option=com_content&amp;amp;view=article&amp;amp;id=284:phd-scholarship-in-digital-heritage-and-virtual-culture-by-dighumlab-and-aarhus-university&amp;amp;catid=3:dariah&amp;amp;Itemid=197</id>
		<summary type="html">&lt;a href=&quot;http://phd.au.dk/gradschools/arts/&quot;&gt;The Graduate School of Arts, Faculty of Arts, Aarhus University&lt;/a&gt; invites applications for a &lt;strong&gt;PhD scholarship in Digital Heritage and Virtual Culture&lt;/strong&gt;. This scholarship is available as of 1 September 2013 for a period of up to three years (5+3) or of up to four years (4+4). Candidates who are awarded the scholarship must commence their PhD programme on1 September 2013.&lt;br /&gt;&lt;br /&gt;Digitized and digital resources with archival institutions such as museums, libraries and research institutions are increasingly being made accessible for research, educational and public use and interaction. Digital resources and data may be both cultural heritage and everyday culture resources, and making such resources accessible and enriching them for innovative research, educational and public use and interaction are central tasks of the digital humanities.&lt;br /&gt;&lt;br /&gt;The Danish Digital Humanities Lab (&lt;a href=&quot;http://dighumlab.dk/&quot;&gt;DIGHUMLAB DK&lt;/a&gt;), anchored at Aarhus University, is a national consortium engaged in digital humanities projects and in developing digital research infrastructures for the humanities and social sciences. With interdisciplinarity and collaborative research at the core of our vision, DIGHUMLAB can offer the PhD scholar collaborative networks with AU research centres (e.g. &lt;a href=&quot;http://www.cavi.dk/&quot;&gt;Centre for Advanced Visualization and Interaction&lt;/a&gt;, Centre for Participatory IT) and with interdisciplinary research environments including Smart Aarhus and the university’s research programmes in digital design, information science, media studies, archaeology, museology, anthropology and experience economy, as well as with international research networks and projects.&lt;br /&gt;</summary>
		<content type="html">&lt;a href=&quot;http://phd.au.dk/gradschools/arts/&quot;&gt;The Graduate School of Arts, Faculty of Arts, Aarhus University&lt;/a&gt; invites applications for a &lt;strong&gt;PhD scholarship in Digital Heritage and Virtual Culture&lt;/strong&gt;. This scholarship is available as of 1 September 2013 for a period of up to three years (5+3) or of up to four years (4+4). Candidates who are awarded the scholarship must commence their PhD programme on1 September 2013.&lt;br /&gt;&lt;br /&gt;Digitized and digital resources with archival institutions such as museums, libraries and research institutions are increasingly being made accessible for research, educational and public use and interaction. Digital resources and data may be both cultural heritage and everyday culture resources, and making such resources accessible and enriching them for innovative research, educational and public use and interaction are central tasks of the digital humanities.&lt;br /&gt;&lt;br /&gt;The Danish Digital Humanities Lab (&lt;a href=&quot;http://dighumlab.dk/&quot;&gt;DIGHUMLAB DK&lt;/a&gt;), anchored at Aarhus University, is a national consortium engaged in digital humanities projects and in developing digital research infrastructures for the humanities and social sciences. With interdisciplinarity and collaborative research at the core of our vision, DIGHUMLAB can offer the PhD scholar collaborative networks with AU research centres (e.g. &lt;a href=&quot;http://www.cavi.dk/&quot;&gt;Centre for Advanced Visualization and Interaction&lt;/a&gt;, Centre for Participatory IT) and with interdisciplinary research environments including Smart Aarhus and the university’s research programmes in digital design, information science, media studies, archaeology, museology, anthropology and experience economy, as well as with international research networks and projects.&lt;br /&gt;</content>
	</entry>
	<entry>
		<title>PhD studentships in Digital Humanities at The Open University</title>
		<link rel="alternate" type="text/html" href="/index.php?option=com_content&amp;view=article&amp;id=282:phd-studentships-in-digital-humanities-at-the-open-university&amp;catid=3:dariah&amp;Itemid=197"/>
		<published>2013-02-21T10:21:02Z</published>
		<updated>2013-02-21T10:21:02Z</updated>
		<id>/index.php?option=com_content&amp;amp;view=article&amp;amp;id=282:phd-studentships-in-digital-humanities-at-the-open-university&amp;amp;catid=3:dariah&amp;amp;Itemid=197</id>
		<summary type="html">The Open University, The British Library, The National Library of Scotland and The National Library of Wales are offering two PhD studentships, funded by the Arts and Humanities Research Council (AHRC), for research based on the collections of one or more of the library partners.&lt;br /&gt;&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;http://www3.open.ac.uk/employment/job-details.asp?id=6754&amp;ref=ext&quot;&gt;Studentship 1 is in History (Digital Heritage/Crowdsourced Data)&lt;/a&gt;, with a particular interest in evaluating or utilising crowdsourced historical data for historical research.&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;http://www3.open.ac.uk/employment/job-details.asp?id=6755&amp;ref=ext&quot;&gt;Studentship 2 is in English (E-Manuscripts/E-Archives&lt;/a&gt;), with a particular emphasis in utilising born-digital e-manuscripts/e-archives for literary research.&lt;/li&gt;&lt;/ul&gt;For further particulars, application forms and terms and conditions, please follow the links above.&lt;br /&gt;&lt;br /&gt;The closing date for applications is &lt;strong&gt;31 March 2013&lt;/strong&gt;.</summary>
		<content type="html">The Open University, The British Library, The National Library of Scotland and The National Library of Wales are offering two PhD studentships, funded by the Arts and Humanities Research Council (AHRC), for research based on the collections of one or more of the library partners.&lt;br /&gt;&lt;ul&gt;&lt;li&gt;&lt;a href=&quot;http://www3.open.ac.uk/employment/job-details.asp?id=6754&amp;ref=ext&quot;&gt;Studentship 1 is in History (Digital Heritage/Crowdsourced Data)&lt;/a&gt;, with a particular interest in evaluating or utilising crowdsourced historical data for historical research.&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;http://www3.open.ac.uk/employment/job-details.asp?id=6755&amp;ref=ext&quot;&gt;Studentship 2 is in English (E-Manuscripts/E-Archives&lt;/a&gt;), with a particular emphasis in utilising born-digital e-manuscripts/e-archives for literary research.&lt;/li&gt;&lt;/ul&gt;For further particulars, application forms and terms and conditions, please follow the links above.&lt;br /&gt;&lt;br /&gt;The closing date for applications is &lt;strong&gt;31 March 2013&lt;/strong&gt;.</content>
	</entry>
	<entry>
		<title>Job offer: Two professorships in Digital Philologies, TU Darmstadt Germany</title>
		<link rel="alternate" type="text/html" href="/index.php?option=com_content&amp;view=article&amp;id=281:job-offer-two-professorships-in-digital-philologies-germany&amp;catid=109:jobs&amp;Itemid=208"/>
		<published>2013-02-20T07:20:01Z</published>
		<updated>2013-02-20T07:20:01Z</updated>
		<id>/index.php?option=com_content&amp;amp;view=article&amp;amp;id=281:job-offer-two-professorships-in-digital-philologies-germany&amp;amp;catid=109:jobs&amp;amp;Itemid=208</id>
		<summary type="html">&lt;p&gt;&lt;font size=&quot;2&quot;&gt;&lt;span style=&quot;font-size: 10pt&quot;&gt;In the past ten years, the Department has established the Digital Humanities with foci in English Corpus and Computational Linguistics as well as German Computer Philology. Throughout this period, the Department has consolidated its position in the digital humanities through internationally networked research activities and the installation of a bilingual Master of Arts program Linguistic and Literary Computing. The specific profile of Digital Humanities as Digital Philologies is going receive further impetus by the installation of a cluster of three professorships representing this discipline. Together with the already existing professorship for German Computational Philology (Andrea Rapp), the two new professorships will form a philology-based cluster of Digital Humanities at TU Darmstadt: &lt;br /&gt;&lt;/span&gt;&lt;/font&gt;&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;font size=&quot;2&quot;&gt;&lt;span style=&quot;font-size: 10pt&quot;&gt; W3 Linguistics with a focus on corpus and computational linguistics, and&lt;/span&gt;&lt;/font&gt;&lt;/li&gt;&lt;li&gt;&lt;font size=&quot;2&quot;&gt;&lt;span style=&quot;font-size: 10pt&quot;&gt;W2 Literary Studies and Cultural Studies with a focus on Digital Literary Studies / Digital Cultural Studies.&lt;/span&gt;&lt;/font&gt;</summary>
		<content type="html">&lt;p&gt;&lt;font size=&quot;2&quot;&gt;&lt;span style=&quot;font-size: 10pt&quot;&gt;In the past ten years, the Department has established the Digital Humanities with foci in English Corpus and Computational Linguistics as well as German Computer Philology. Throughout this period, the Department has consolidated its position in the digital humanities through internationally networked research activities and the installation of a bilingual Master of Arts program Linguistic and Literary Computing. The specific profile of Digital Humanities as Digital Philologies is going receive further impetus by the installation of a cluster of three professorships representing this discipline. Together with the already existing professorship for German Computational Philology (Andrea Rapp), the two new professorships will form a philology-based cluster of Digital Humanities at TU Darmstadt: &lt;br /&gt;&lt;/span&gt;&lt;/font&gt;&lt;/p&gt;&lt;ul&gt;&lt;li&gt;&lt;font size=&quot;2&quot;&gt;&lt;span style=&quot;font-size: 10pt&quot;&gt; W3 Linguistics with a focus on corpus and computational linguistics, and&lt;/span&gt;&lt;/font&gt;&lt;/li&gt;&lt;li&gt;&lt;font size=&quot;2&quot;&gt;&lt;span style=&quot;font-size: 10pt&quot;&gt;W2 Literary Studies and Cultural Studies with a focus on Digital Literary Studies / Digital Cultural Studies.&lt;/span&gt;&lt;/font&gt;</content>
	</entry>
</feed>
