<?xml version="1.0" encoding="utf-8"?>
<!-- generator="Joomla! 1.5 - Open Source Content Management" -->
<?xml-stylesheet href="/components/com_jcomments/tpl/default/style.css?v=10" type="text/css"?>
<rss version="2.0">
	<channel>
		<title>Latest News</title>
		<description></description>
		<link>http://localhost:8666/index.php?option=com_content&amp;view=category&amp;id=3&amp;layout=blog&amp;Itemid=197</link>
		<lastBuildDate>Thu, 18 Apr 2013 09:31:22 +0000</lastBuildDate>
		<generator>Joomla! 1.5 - Open Source Content Management</generator>
		<language>en-gb</language>
		<item>
			<title>CFP: Cultural Heritage, Creative Tools and Archives Workshop</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=291:cfp-cultural-heritage-creative-tools-and-archives-workshop&amp;catid=3:dariah&amp;Itemid=197</link>
			<description><![CDATA[<p><a href="http://dighumlab.dk/"><img src="http://localhost:8666/images/M_images/dighumlab.jpg" border="0" hspace="10" vspace="10" width="200" height="56" align="right" /><img src="http://localhost:8666/images/stories/dcu_logo_en.png" border="0" hspace="10" vspace="10" width="200" align="right" />DIGHUMLAB DK</a> and the <a href="http://www.dcu.gr/">DIGITAL CURATION UNIT</a> Athens are pleased to invite you to submit to a DARIAH associated 2 day workshop on CULTURAL HERITAGE, CREATIVE TOOLS AND ARCHIVES.<br />The workshop is open to all but we in particular invite participants drawn in the first instance from the DARIAH, ARIADNE, CENDARI and NeDiMAH and other EU cultural heritage networks. We envisage it will foster the growth of a community of practice in the field of digital heritage and digital humanities, leading to closer cooperation between participants and helping attendees develop tools and methods that can be used by the wider community.</p><p><strong>Central topics:</strong></p><ul><li>    Presentation of digital heritage tools and infrastructures (database, knowledge representation, analysis).</li><li>    GIS, 3D graphic reconstruction, high end imaging.</li><li>    Ontology related to archives and database storage for material and visual culture, etc. and how best to share data and tools across European countries and partners.</li><li>    Database and infrastructure support for fieldwork (cf. issues of data collecting and representation, excavation and survey data management, recording "information at the trowel's edge" to coin Ian Hodder, how to best process survey and long series datasets etc.).</li><li>    Discussion on further collaboration and how to influence EU policy in digital heritage-cultural heritage matters.</li></ul><strong>Presentation formats:</strong><br /><ul><li>    Project presentation 20 minutes.</li><li>    Demonstration 20 minutes of tool or method or project.</li><li>    Paper presentation 20 minutes presentation. Final papers may be published in a journal (to be advised).</li><li>    Panel 40-60 minutes involving 3-5 speakers.]]></description>
			<category>DARIAH</category>
			<pubDate>Wed, 03 Apr 2013 10:07:27 +0000</pubDate>
		</item>
		<item>
			<title>Hack4LT, 4 - 5 April 2013, Vilnius, Lithuania</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=290:hack4lt-4-5-april-2013-vilnius-lithiania&amp;catid=3:dariah&amp;Itemid=197</link>
			<description><![CDATA[<p><img src="http://localhost:8666/images/stories/hack4lt_agenda_seite_1.jpg" border="0" hspace="10" vspace="10" height="200" align="right" /><strong>Hack4LT</strong>: The first cultural heritage and digital humanities orientated hackathon in Lithuania will take place on 04 - 05 April 2013 in Vilnius, Lithuania<br /> <strong>Inspired by:</strong> EUROPEANA and DARIAH<br /> <strong>Organisators:</strong> Vilnius University Faculty of Communication (VUFC) (<a href="http://www.kf.vu.lt/en">http://www.kf.vu.lt/en</a>) and Vilnius University Library (VUL) <a href="http://localhost:8666/(http://www.mb.vu.lt/en/titulinis">(http://www.mb.vu.lt/en/titulinis</a>)<br />Partners: M. Mažvydas National Library of Lithuania (NLL) (<a href="http://www.lnb.lt/en/">http://www.lnb.lt/en/</a>) and „Dizi“ (<a href="http://www.dizi.lt/heritage/index_en.php">http://www.dizi.lt/heritage/index_en.php</a>)<br />Sponsors: Vilnius University (VU) (<a href="http://www.vu.lt/en">http://www.vu.lt/en</a>) and "Asseco Lietuva" (<a href="http://www.sintagma.lt/sintagma/selectLanguage.do?language=en">http://www.sintagma.lt/sintagma/selectLanguage.do?language=en</a>).<br /><strong>Venue:</strong> National Open Access Scholarly Communication and Information Center (http://www.mkic.mb.vu.lt/en/), Address: Saulėtekio av. 5, Vilnius, Lithuania (https://foursquare.com/v/mkic--vilniaus-universiteto-biblioteka/5110af35e4b00d9b65a437c1<br /><a href="https://email.gwdg.de/owa/redir.aspx?C=l4lMj_G9RUWmr68PN0XBso9uktTD8c8I1I_q3wjVcFdN0szArdK23ElhtjUJx9pn9VrTPajroQo.&URL=https%3a%2f%2ffoursquare.com%2fv%2fmkic--vilniaus-universiteto-biblioteka%2f5110af35e4b00d9b65a437c1" target="_blank"></a></p><p><strong>Description:</strong><br /> Hack4LT is a two-day event intended to stimulate the collaboration  between Humanities' scholars and software developers. Its aim is  targeted towards the technology driven experimentation with an existing  EUROPEANA data sets connecting various kinds of digitized  cultural heritage resources from the European museums, libraries,  archives, etc. Free access to these resources stimulates a broad public  interest in the European culture and challenges cultural institutions to  seek new ways of engaging people, as well as  to develops tools in this space. Furthermore, because of the richness  of EUROPEANA collection and the nature of a preserved digital content it  is considered to be a valuable data source for the researchers of the  Digital Humanities and enhances digitally-enabled  research in this area.</p>]]></description>
			<category>DARIAH</category>
			<pubDate>Mon, 11 Mar 2013 09:12:35 +0000</pubDate>
		</item>
		<item>
			<title>Italy signed Memorandum of Understanding</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=289:italy-signed-memorandum-of-understanding&amp;catid=3:dariah&amp;Itemid=197</link>
			<description><![CDATA[<p><a href="http://www.cnr.it/sitocnr/Englishversion/Englishversion.html"><img src="http://localhost:8666/images/stories/dariah-it-logo-no-tagline-rgb.png" border="0" hspace="10" vspace="10" width="180" align="right" /></a>We are delighted to announce that Italy has signed the Memorandum of Understanding (MoU) formally expressing their interest in participating in DARIAH.</p><p>DARIAH-IT activities will be coordinated by the the <a href="http://www.cnr.it/sitocnr/Englishversion/Englishversion.html">National Research Council</a>.</p>]]></description>
			<category>DARIAH</category>
			<pubDate>Fri, 08 Mar 2013 13:01:47 +0000</pubDate>
		</item>
		<item>
			<title> Bamboo DiRT and DH Commons looking for DARIAH representatives</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=288:-bamboo-dirt-and-dh-commons-looking-for-dariah-representatives&amp;catid=3:dariah&amp;Itemid=197</link>
			<description><![CDATA[<p><img src="http://localhost:8666/images/stories/dhcommons_logo.jpg" border="0" hspace="10" vspace="10" width="200" align="right" /> <img src="http://localhost:8666/images/stories/bamboo_dirt.jpg" border="0" hspace="10" vspace="10" width="200" height="42" align="right" />Bamboo DiRT and DH Commons are looking for DARIAH representatives. </p><p>1. A DARIAH representative on the board of <a href="http://dirt.projectbamboo.org/">Bamboo DiRT</a></p><p>Quinn Dombroski from Bamboo DiRT would be happy to add contents from DARIAH directory of tools (including DARIAH seal), and to welcome a DARIAH member in her editorial board.</p><p>2. A DARIAH representative as co-editor for<a href="http://dhcommons.org/"> DHCommons</a></p><p>The role of the co-editor coming from a non US and preferably non English speaking country would be to work on a weekly basis on collecting reviews and suggesting new projects in the database. DHCommons is seeking a co-editor with a different speciality than co-editor Ryan Cordell who is active in the literature, geolocalisation in texts, social networks areas.</p><p>If you are interested, please contact  Marin Dacos (<a href="http://localhost:8666/mailto:marin.dacos@openedition.org">marin.dacos at openedition.org</a>) or Erik Champion (<a href="http://localhost:8666/mailto:echa@adm.au.dk">echa at adm.au.dk</a>)</p>]]></description>
			<category>DARIAH</category>
			<pubDate>Fri, 08 Mar 2013 07:31:04 +0000</pubDate>
		</item>
		<item>
			<title>THATCamp London, registration now open</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=287:thatcamp-london-registration-now-open&amp;catid=3:dariah&amp;Itemid=197</link>
			<description><![CDATA[<p>THAT Camp London is now open for registration. This one-day unconference will take place on 14 April 2013 at the British Library. This event coincides with the <a href="https://uk.wikimedia.org/wiki/GLAM-WIKI_2013">GLAM-WIKI conference</a>, which runs on Friday 12 and Saturday 13 April 2013.</p><p>For further information please visit this page: <a href="http://london2013.thatcamp.org/">http://london2013.thatcamp.org/ </a></p><p>Further upcoming THATCamps can be found here: <a href="http://thatcamp.org/en/">http://thatcamp.org/en/ </a></p>]]></description>
			<category>DARIAH</category>
			<pubDate>Thu, 28 Feb 2013 07:20:01 +0000</pubDate>
		</item>
		<item>
			<title>First CENDARI Summer School, 22 - 26 July 2013</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=285:first-cendari-summer-school-22-26-july-2013&amp;catid=3:dariah&amp;Itemid=197</link>
			<description><![CDATA[<img src="http://localhost:8666/images/stories/cendari.jpg" border="0" hspace="10" vspace="10" width="180" height="62" align="right" />The <a href="http://www.cendari.eu/">CENDARI</a> (Collaborative European Digital Archive Infrastructure) project, in collaboration with the COST Action: IS 1005, 'Medioevo Europeo: Medieval Studies and Technological Resources', will host the first of three annual CENDARI Summer Schools, 22 - 26 July 2013 in Florence, Italy. The Summer School, entitled <strong>Historical Sources & Transnational Approaches to European History</strong>, will invite participants to address specifically how CENDARI aims to resolve the difficulties of historical research through the application of digital technologies and methods. For more information and to <strong>apply before the 15th April 2013</strong>, please visit <a href="http://www.cendari.eu/news-events/summer-school-2013/">http://www.cendari.eu/news-events/summer-school-2013/</a>.<br /><br />Sessions will apply the concept of 'transnational moments' to examine ways in which historical research is complicated by the nature of material records of the past. The Summer School will provide a context for the various collections-level challenges to transnational history, such as how to identify sources that have become 'hidden' or lost through accidents of history. Researchers will examine the linguistic, quantitative and methodological challenges facing them today.<br />]]></description>
			<category>DARIAH</category>
			<pubDate>Fri, 22 Feb 2013 09:12:52 +0000</pubDate>
		</item>
		<item>
			<title>OpenEdition Books! Now open</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=283:openedition-books-now-open&amp;catid=3:dariah&amp;Itemid=197</link>
			<description><![CDATA[After <a href="http://www.openedition.org/">Revues.org </a>(1999), <a href="http://calenda.org/">Calenda</a> (2000) and <a href="http://hypotheses.org/">Hypothèses</a> (2008), OpenEdition’s fourth platform appeared Wednesday 20th February 2013. <a href="http://books.openedition.org/">OpenEdition Books</a> is the final addition to our comprehensive series of publishing platforms for the humanities and social sciences. The new service is the book distribution platform on the OpenEdition portal, a non-profit-making initiative whose aim is to develop Open Access to research results in the humanities, social sciences and beyond. The service is not an ideological gesture. It is a genuine academic program, in which ideas are seen as seeds that require constant cross-fertilisation to attain their full potential. OpenEdition is run by the Centre for Open Electronic Publishing, the Université d’Aix-Marseille, the EHESS and the Université d’Avignon, and financed by the French national research agency within the framework of their Facilities of Excellence program.<br />]]></description>
			<category>DARIAH</category>
			<pubDate>Fri, 22 Feb 2013 08:16:27 +0000</pubDate>
		</item>
		<item>
			<title>PhD scholarship  in Digital Heritage and Virtual Culture by DIGHUMLAB and Aarhus University</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=284:phd-scholarship-in-digital-heritage-and-virtual-culture-by-dighumlab-and-aarhus-university&amp;catid=3:dariah&amp;Itemid=197</link>
			<description><![CDATA[<a href="http://phd.au.dk/gradschools/arts/">The Graduate School of Arts, Faculty of Arts, Aarhus University</a> invites applications for a <strong>PhD scholarship in Digital Heritage and Virtual Culture</strong>. This scholarship is available as of 1 September 2013 for a period of up to three years (5+3) or of up to four years (4+4). Candidates who are awarded the scholarship must commence their PhD programme on1 September 2013.<br /><br />Digitized and digital resources with archival institutions such as museums, libraries and research institutions are increasingly being made accessible for research, educational and public use and interaction. Digital resources and data may be both cultural heritage and everyday culture resources, and making such resources accessible and enriching them for innovative research, educational and public use and interaction are central tasks of the digital humanities.<br /><br />The Danish Digital Humanities Lab (<a href="http://dighumlab.dk/">DIGHUMLAB DK</a>), anchored at Aarhus University, is a national consortium engaged in digital humanities projects and in developing digital research infrastructures for the humanities and social sciences. With interdisciplinarity and collaborative research at the core of our vision, DIGHUMLAB can offer the PhD scholar collaborative networks with AU research centres (e.g. <a href="http://www.cavi.dk/">Centre for Advanced Visualization and Interaction</a>, Centre for Participatory IT) and with interdisciplinary research environments including Smart Aarhus and the university’s research programmes in digital design, information science, media studies, archaeology, museology, anthropology and experience economy, as well as with international research networks and projects.<br />]]></description>
			<category>DARIAH</category>
			<pubDate>Fri, 22 Feb 2013 07:29:29 +0000</pubDate>
		</item>
		<item>
			<title>PhD studentships in Digital Humanities at The Open University</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=282:phd-studentships-in-digital-humanities-at-the-open-university&amp;catid=3:dariah&amp;Itemid=197</link>
			<description><![CDATA[The Open University, The British Library, The National Library of Scotland and The National Library of Wales are offering two PhD studentships, funded by the Arts and Humanities Research Council (AHRC), for research based on the collections of one or more of the library partners.<br /><ul><li><a href="http://www3.open.ac.uk/employment/job-details.asp?id=6754&ref=ext">Studentship 1 is in History (Digital Heritage/Crowdsourced Data)</a>, with a particular interest in evaluating or utilising crowdsourced historical data for historical research.</li><li><a href="http://www3.open.ac.uk/employment/job-details.asp?id=6755&ref=ext">Studentship 2 is in English (E-Manuscripts/E-Archives</a>), with a particular emphasis in utilising born-digital e-manuscripts/e-archives for literary research.</li></ul>For further particulars, application forms and terms and conditions, please follow the links above.<br /><br />The closing date for applications is <strong>31 March 2013</strong>.]]></description>
			<category>DARIAH</category>
			<pubDate>Thu, 21 Feb 2013 10:21:02 +0000</pubDate>
		</item>
		<item>
			<title>DARIAH seminar session at EHESS</title>
			<link>http://localhost:8666/index.php?option=com_content&amp;view=article&amp;id=280:dariah-seminar-session-at-ehess&amp;catid=3:dariah&amp;Itemid=197</link>
			<description><![CDATA[On 13 February 2013, Sophie David, French DARIAH coordinator, and Marin Dacos, DARIAH VCC task leader, have been invited by <a href="http://www.ehess.fr/fr/ecole/">L'École des hautes études en sciences sociales</a> to present and discuss about DARIAH with European students during the seminar "<a href="http://www.ehess.fr/fr/enseignement/enseignements/2012/ue/324/">Digital Humanities. Les transformations numériques du rapport aux savoirs</a>".]]></description>
			<category>DARIAH</category>
			<pubDate>Wed, 13 Feb 2013 09:34:25 +0000</pubDate>
		</item>
	</channel>
</rss>
